# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['created_at'], 'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
        migrations.AddField(
            model_name='rooms',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rooms',
            name='supplies',
            field=models.ManyToManyField(related_name='get_supplies', to='rooms.Supplies', verbose_name='Supply'),
        ),
    ]
