# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20180828_0242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplies',
            options={'ordering': ['created_at'], 'verbose_name': 'supply', 'verbose_name_plural': 'supplies'},
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='supplies',
            old_name='name',
            new_name='title',
        ),
    ]
