# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20180828_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Status'),
        ),
    ]
