# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20180828_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='capacity',
            new_name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='user',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
