# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0006_auto_20180828_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=1)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Rooms')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'verbose_name': 'reserv',
                'verbose_name_plural': 'reservs',
            },
        ),
    ]
