# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_reservroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservroom',
            name='additional_supplies',
            field=models.ManyToManyField(related_name='get_addtional_supplies', to='rooms.Supplies', verbose_name='Additional Supply'),
        ),
    ]
