# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_reservroom_additional_supplies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default=None, max_length=15, null=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'verbose_name': 'disponibility',
                'verbose_name_plural': 'disponibilities',
            },
        ),
        migrations.AddField(
            model_name='rooms',
            name='disponiblity',
            field=models.ManyToManyField(to='rooms.Disponibilities'),
        ),
    ]
