# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20180828_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='disponiblity',
        ),
        migrations.AddField(
            model_name='rooms',
            name='disponiblity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Disponibilities'),
        ),
    ]
