# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20180828_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='disponiblity',
        ),
        migrations.AddField(
            model_name='rooms',
            name='disponiblity',
            field=models.ManyToManyField(related_name='get_disponibilities', to='rooms.Disponibilities', verbose_name='Disponibility'),
        ),
    ]
