# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_auto_20180828_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservroom',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='reservroom',
            name='to_date',
        ),
        migrations.AddField(
            model_name='reservroom',
            name='hours',
            field=models.ManyToManyField(related_name='get_reserv_hours', to='rooms.Disponibilities', verbose_name='Hours reserved'),
        ),
    ]
